#!/usr/bin/env bash
# User specific environment and startup programs
alias ngxedcf='vim /srv/nginx/conf/nginx.conf'
alias ngxtlfa='tail -f /var/log/nginx/access.log'
alias ngxtlfe='tail -f /var/log/nginx/error.log'
alias ngxrld='systemctl daemon-reload && sleep 1 && systemctl reload nginxd.service && sleep 2  && systemctl status nginxd.service'
alias ngxrsd='systemctl daemon-reload && sleep 1 && systemctl stop nginxd.service && sleep 2  && systemctl start nginxd.service && sleep 2 && systemctl status nginxd.service'
